job-defaults: &job-defaults
  working_directory: &working_directory
    ~/product
  machine:
    image: ubuntu-2004:202104-01
    docker_layer_caching: true

version: 2

jobs:
  test-local:
    <<: *job-defaults
    steps:
      - checkout
      - run: |
          ./scripts/run-tests.sh

  test-e2e:
    <<: *job-defaults
    steps:
      - checkout
      - run: |
          ./scripts/publish.sh && \
          ./scripts/run-tests-e2e.sh

  publish:
    <<: *job-defaults
    steps:
      - checkout
      - run: |
          export LIB_VERSION=${CIRCLE_TAG} && \
          ./scripts/publish.sh

workflows:
  version: 2

  build-test-and-publish:
    jobs:
      - test-local:
          context: circleci
          filters:
            branches:
              only: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/

      - test-e2e:
          context: circleci
          requires:
            - test-local
          filters:
            branches:
              only: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/

      - publish:
          context: circleci
          requires:
            - test-e2e
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
